### ISSUE TITLE
Priority dropdown

### ISSUE THREAD

**Issue by ruXlab** [Yukichka/TODOLIST#2]
It should be possible to specify priority of the task during it's creation and this priority has to be displayed with relevant colour next to the todo item text

Similar to:

```
* Buy milk [URGENT]
  02/03/92 11:32 [CHANGE]  [REMOVE]  
. . . . 
. . . .

[INPUT TEXT for todo item] [PRIORITY dropdown] [ADD button]
```

**Comment by Yukichka** [comment]
Fixed in 0e36ea4
