### ISSUE TITLE
Introduce bootstrap support for styling 

### ISSUE THREAD

**Issue by ruXlab** [Yukichka/TODOLIST#3]
It would be nice to have stylized todo app using bootstrap framework

What can be stylized using bootstrap
1) Whole page skeleton like [here](https://getbootstrap.com/docs/4.0/examples/)
2) Badges for priority [like here](https://getbootstrap.com/docs/4.0/components/badge/)
3) Input/form style [like here](https://getbootstrap.com/docs/4.0/components/input-group/#multiple-inputs)

**Comment by Yukichka** [comment]
Fixed in b356122
