### ISSUE TITLE
Implement 'deleteToDo(id)` function

### ISSUE THREAD

**Issue by ruXlab** [Yukichka/TODOLIST#5]
Function has to change dataset accordingly and re-render it, potentially could be implemented as following algorithm:

- Find record by id
- Remove record from dataset
- Re-render representation by calling `render()` function

Alternatively same result can be achieved using functional approach:

- Filter dataset for record with id to be excluded using  [Array.filter function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
- Re-render representation by calling `render()` function

`deleteToDo(id)` accepts unique id of record to be removed as parameter and can be called as a click handler of the button

**Comment by Yukichka** [comment]
Could you check in ff5e4e4  pls

**Comment by Yukichka** [comment]
and in 198beb7

**Comment by Yukichka** [comment]
Hm I think I did wrong approach, I don't think I did as you mentioned

**Comment by Yukichka** [comment]
fixed in 793fea9

**Comment by ruXlab** [comment]
793fea9 fixes #6 not this one :)

**Comment by Yukichka** [comment]
fixed in 0479d68
