### ISSUE TITLE
html layout for sort buttons

### ISSUE THREAD

**Issue by ruXlab** [Yukichka/TODOLIST#7]
For user convenience need to add button which allow to sort todos 

Placement is up to developer, for instance it could be bootstrap's navigation bar or floating group of buttons above or below of the list

As from UI point of view bootstrap's [button groups](https://getbootstrap.com/docs/4.1/components/button-group/?#button-toolbar) can be used 

Required buttons:
* ↑ time
* ↓ time
* ↑ priority
* ↓ priority

**Comment by Yukichka** [comment]
Fixed in 2cafa0c

**Comment by ruXlab** [comment]
👍👍👍👍

On 6 May 2018 6:21 pm, "Yukichka" <notifications@github.com> wrote:

Closed #7 <https://github.com/Yukichka/TODOLIST/issues/7>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Yukichka/TODOLIST/issues/7#event-1611776996>, or mute
the thread
